export const RESPONSE_CODES = {
  SUCCESS: 'SUCCESS',
  CREATED: 'CREATED',
  // Domain-specific codes
  USER_PROFILE_FETCHED: 'USER_PROFILE_FETCHED',
  USER_PASSWORD_UPDATED: 'USER_PASSWORD_UPDATED',
  USER_GLOBALNAME_UPDATED: 'USER_GLOBALNAME_UPDATED',
  USER_CUSTOM_STATUS_UPDATED: 'USER_CUSTOM_STATUS_UPDATED',
  USER_USERNAME_UPDATED: 'USER_USERNAME_UPDATED',
  FRIEND_REQUEST_SENT: 'FRIEND_REQUEST_SENT',
  FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
  FRIEND_REQUEST_REJECTED: 'FRIEND_REQUEST_REJECTED',
  FRIEND_REQUEST_CANCELLED: 'FRIEND_REQUEST_CANCELLED',
  FRIENDS_FETCHED: 'FRIENDS_FETCHED',
  PRESENCE_STATUS_UPDATED: 'PRESENCE_STATUS_UPDATED',
  RELATION_SAVED: 'RELATION_SAVED',
  RELATION_REMOVED: 'RELATION_REMOVED',
  RELATIONS_FETCHED: 'RELATIONS_FETCHED',
  RELATION_NOTE_UPDATED: 'RELATION_NOTE_UPDATED',
  RELATION_STATS_FETCHED: 'RELATION_STATS_FETCHED',
  // Errors
  SERVER_ERROR: 'SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type ResponseCode = (typeof RESPONSE_CODES)[keyof typeof RESPONSE_CODES];
