const MIME_BY_EXTENSION: Record<string, string> = {
  js: 'text/javascript',
  mjs: 'text/javascript',
  cjs: 'text/javascript',
  jsx: 'text/jsx',
  ts: 'text/typescript',
  mts: 'text/typescript',
  tsx: 'text/tsx',
  json: 'application/json',
  jsonc: 'application/json',
  css: 'text/css',
  scss: 'text/scss',
  sass: 'text/x-sass',
  less: 'text/less',
  html: 'text/html',
  htm: 'text/html',
  xml: 'text/xml',
  svg: 'image/svg+xml',
  md: 'text/markdown',
  markdown: 'text/markdown',
  txt: 'text/plain',
  log: 'text/plain',
  c: 'text/x-c',
  h: 'text/x-c',
  cpp: 'text/x-c++',
  hpp: 'text/x-c++',
  cc: 'text/x-c++',
  cxx: 'text/x-c++',
  java: 'text/x-java',
  py: 'text/x-python',
  rb: 'text/x-ruby',
  php: 'text/x-php',
  go: 'text/x-go',
  rs: 'text/x-rust',
  swift: 'text/x-swift',
  kotlin: 'text/x-kotlin',
  kt: 'text/x-kotlin',
  sh: 'text/x-shell',
  bash: 'text/x-shell',
  zsh: 'text/x-shell',
  yml: 'text/yaml',
  yaml: 'text/yaml',
  toml: 'text/x-toml',
  ini: 'text/plain',
  conf: 'text/plain',
  env: 'text/plain',
  sql: 'text/x-sql',
  vue: 'text/vue',
  svelte: 'text/svelte',
  dart: 'text/x-dart',
  csv: 'text/csv',
  diff: 'text/x-diff',
  patch: 'text/x-diff',
  graphql: 'text/graphql',
  gql: 'text/graphql',
  dockerfile: 'text/plain',
  makefile: 'text/plain',
  prisma: 'text/plain',
};

export function getMimeType(filename: string): string {
  const dotIndex = filename.lastIndexOf('.');
  const extension =
    dotIndex === -1 ? '' : filename.slice(dotIndex + 1).toLowerCase();

  return MIME_BY_EXTENSION[extension] ?? 'text/plain';
}
